### ISSUE TITLE
verify audio cues play within unity app

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-unity-client#1]
- the audio cue's accessible alternative must be output as an event
- the cohort session should fire global events on cue start / stop / etc
- error handling must be included

**Comment by jakemoves** [comment]
- verify using sample cues (cueNumber: 1, 2, 3)
- default "working" occasion is id:3
- verify sending to another occasion does not have any results within app (you should see some kind of error code in Postman)
- mediaDomain for audio is 0
- check cueActions:
  - 0: play / go / on
  - 1: pause / off
  - 2: restart
  - 3: stop / off (?)

**Comment by AmandaLBaker** [comment]
Note: audio cues only play if headphones are plugged in, or ringer is turned on.

**Comment by AmandaLBaker** [comment]
Audio cues are only stopped by the interruption of other audio cues, or if it plays to completion. If a video, haptic, or text cue is sent, the sound cue will continue playing to completion overtop of these other cues. If the video has sound, this means two sounds files are playing simultaneously.
