### ISSUE TITLE
verify haptic cue works within the Unity app

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-unity-client#4]
- single vibe on single cue

**Comment by jakemoves** [comment]
Ok, this is implemented. Note that haptics cues (mediaDomain 4) don't use most of the other details sent in the cue message. The Unity client looks at the targetTags to make sure this device should respond, and then makes it vibrate. That's it :)

**Comment by jakemoves** [comment]
to test:
- broadcast from Postman
- set mediaDomain to 4
- cueAction, cueNumber should not matter

**Comment by AmandaLBaker** [comment]
Note: cues to vibrate only work if "vibrate on ring" or "vibrate on silent" is enabled in user's phone settings and their ringer is on the corresponding setting. Otherwise, the vibration won't occur.

(Assume this is just an inevitable based on how iPhones work, but want to double check)

**Comment by jakemoves** [comment]
Yup, this is expected behaviour. @AmandaLBaker this would be a good thing to flag in documentation, please make sure it gets there.
